
services:
  frontend:
    build:
      context: .
      dockerfile: iac_dockerfile
      no_cache: true
    image: iac-demo
    ports:
      - "5000:80"
      - "5001:80"  
    hostname: My-file
    container_name: frontend-container

