
services:
  frontend:
    build:
      context: .
      dockerfile: iac_dockerfile
    image: iac-demo
    ports:
      - "8046:80"
      - "8067:80"  
    hostname: My-file
    container_name: frontend-container

