version: '3'
services:
  frontend:
    build:
      context: .
      dockerfile: iac_dockerfile
    image: iac-demo
    ports:
      - "8046:80"
    hostname: My-file
    container_name: frontend-container
  backend:
    image: nginx
    ports:
      - "8067:80"

